import { TuiTheme } from "../types/index.js";

export const DEFAULT_THEME: TuiTheme = {
  name: "Forest Default",
  colors: {
    headerBg: "magenta",
    headerFg: "white",
    footerBg: "blue",
    footerFg: "white",
    sectionHeaderFg: "cyan",
    listHeaderFg: "magenta",
    listSelectionBg: "yellowBright",
    listSelectionFg: "black",
    listUnreadFg: "#CCCCCC",
    listReadFg: "#CCCCCC",
    scrollbarBg: "gray",
    scrollbarFg: "white",
    readerTitleFg: "yellow",
    readerBookmarkFg: "magenta",
    readerLinkFg: "cyan",
    readerSummaryLabelFg: "green",
    readerStatusFg: "blue",
    readerErrorFg: "red",
    errorFg: "red",
    warningFg: "yellow",
    successFg: "green",
    infoFg: "white",
  },
};

export const OCEAN_THEME: TuiTheme = {
  name: "Ocean",
  colors: {
    headerBg: "blue",
    headerFg: "white",
    footerBg: "cyan",
    footerFg: "black",
    sectionHeaderFg: "cyan",
    listHeaderFg: "cyan",
    listSelectionBg: "blue",
    listSelectionFg: "white",
    listUnreadFg: "#CCCCCC",
    listReadFg: "#CCCCCC",
    scrollbarBg: "blue",
    scrollbarFg: "cyan",
    readerTitleFg: "cyan",
    readerBookmarkFg: "yellow",
    readerLinkFg: "cyan",
    readerSummaryLabelFg: "cyan",
    readerStatusFg: "blue",
    readerErrorFg: "red",
    errorFg: "red",
    warningFg: "yellow",
    successFg: "green",
    infoFg: "white",
  },
};

export const FOREST_THEME: TuiTheme = {
  name: "Deep Forest",
  colors: {
    headerBg: "green",
    headerFg: "white",
    footerBg: "black",
    footerFg: "green",
    sectionHeaderFg: "green",
    listHeaderFg: "green",
    listSelectionBg: "green",
    listSelectionFg: "black",
    listUnreadFg: "#CCCCCC",
    listReadFg: "#CCCCCC",
    scrollbarBg: "black",
    scrollbarFg: "green",
    readerTitleFg: "green",
    readerBookmarkFg: "yellow",
    readerLinkFg: "cyan",
    readerSummaryLabelFg: "green",
    readerStatusFg: "green",
    readerErrorFg: "red",
    errorFg: "red",
    warningFg: "yellow",
    successFg: "green",
    infoFg: "white",
  },
};

export const MONOCHROME_THEME: TuiTheme = {
  name: "Monochrome",
  colors: {
    headerBg: "gray",
    headerFg: "white",
    footerBg: "gray",
    footerFg: "white",
    sectionHeaderFg: "white",
    listHeaderFg: "white",
    listSelectionBg: "gray",
    listSelectionFg: "white",
    listUnreadFg: "#CCCCCC",
    listReadFg: "#CCCCCC",
    scrollbarBg: "black",
    scrollbarFg: "gray",
    readerTitleFg: "white",
    readerBookmarkFg: "gray",
    readerLinkFg: "cyan",
    readerSummaryLabelFg: "white",
    readerStatusFg: "gray",
    readerErrorFg: "red",
    errorFg: "red",
    warningFg: "yellow",
    successFg: "green",
    infoFg: "white",
  },
};

export const WALLSTREET_THEME: TuiTheme = {
  name: "Wall Street",
  colors: {
    headerBg: "#000000",
    headerFg: "#FFA028",
    footerBg: "#000000",
    footerFg: "#FFA028",
    sectionHeaderFg: "#FFA028",
    listHeaderFg: "#FFFF00",
    listSelectionBg: "#0068FF",
    listSelectionFg: "#FFFFFF",
    listUnreadFg: "#FFA028",
    listReadFg: "#FFA028",
    scrollbarBg: "gray",
    scrollbarFg: "#FFA028",
    readerTitleFg: "#FFA028",
    readerBookmarkFg: "#FFFF00",
    readerLinkFg: "#0068FF",
    readerSummaryLabelFg: "#FFFF00",
    readerStatusFg: "#FFA028",
    readerErrorFg: "#FF0000",
    errorFg: "#FF0000",
    warningFg: "#FFFF00",
    successFg: "#00FF00",
    infoFg: "#FFA028",
  },
};

export const THEMES = [
  DEFAULT_THEME,
  OCEAN_THEME,
  FOREST_THEME,
  MONOCHROME_THEME,
  WALLSTREET_THEME,
];
