/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function fetchLinks(url: string): Promise<Array<LinkInfo>>

export declare function fetchLinksAsync(url: string): Promise<Array<LinkInfo>>

export interface LinkInfo {
  url: string
  text: string
}
